name: PHPStan

on:
  push:
  pull_request:
    branches:
      - main

concurrency:
  group: phpstan-${{ github.ref_name || github.run_id }}
  cancel-in-progress: true

jobs:

  phpstan:
    name: PHPStan PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-progress --prefer-dist --optimize-autoloader"

      - name: Larastan
        run: php ./vendor/bin/phpstan analyse --memory-limit=2G --error-format=github
